"""Constants for the Shelly 3m Emulator for MQTT integration."""

DOMAIN = "shelly_3em_emulator_4mqtt"
CONF_MQTT_BROKER = "MQTT_BROKER"
CONF_MQTT_POWER_TOPIC = "MQTT_POWER_TOPIC"
CONF_MQTT_POWER_PHASE1_TOPIC = "MQTT_POWER_PHASE1_TOPIC"
CONF_MQTT_POWER_PHASE2_TOPIC = "MQTT_POWER_PHASE2_TOPIC"
CONF_MQTT_POWER_PHASE3_TOPIC = "MQTT_POWER_PHASE3_TOPIC"
CONF_MQTT_POWER_PHASEALL_TOPIC = "MQTT_POWER_PHASEALL_TOPIC"

DEFAULT_MQTT_PORT = "1883"
